---
# Celery/RabbitMQ settings

rabbit_packages:
  - rabbitmq-server 

galaxy_rabbit_hostname: "localhost"
galaxy_rabbit_port: 5672
galaxy_rabbit_vhost: "/galaxy"
galaxy_rabbit_username: "galaxy"
galaxy_rabbit_password: "galaxy"

