---

- name: restart postgres
  service: name=postgresql state=restarted

- name: restart apache
  service: name=httpd state=started

- name: restart celeryd
  supervisorctl:
    config: "/etc/supervisord.conf"
    name: "galaxy-celeryd"
    state: started
