# create-admin-user.yml
#
# Creates a django superuser account. Uses Ansible's expect modules, which expects to find the Python
# pexpct module installed on the target host.
#
# run cmd: ansible-playbook -i ec2.py --extra-vars="@your-var-file.yml" create-admin-user.yml
#

- name: Create admin user
  hosts: "{{ galaxy_hosts_web }}"
  gather_facts: no
  become: yes
  roles:
    # Only runs on the first host found in the group
    - role: create-admin-user
      when: inventory_hostname == groups[galaxy_hosts_web][0] 
