# jenkins.yml
#
#  Create a user account and add authorized_keys for jenkins. Assumes jenkins is defined in authorized-users.yml
#
#  run cmd: ansible-playbook -i ec2.py --extra-vars="@your-vars-file.yml" jenkins.yml
#
---
- name: Create user jenkins
  hosts: "{{ galaxy_hosts_all }}"
  gather_facts: no
  vars_files: 
     - authorized-users.yml
  become: yes

  tasks: 

    - name: Create jenkins user 
      user:
        name: "{{ jenkins.username }}" 
        state: present
        createhome: yes
        groups: wheel
        shell: "/bin/bash"

    - name: Add authorized_keys
      authorized_key:
        state: present
        user: "{{ jenkins.username }}" 
        key: "{{ item }}" 
      with_items: "{{ jenkins.ssh_keys }}"

