- name: determine if selinux is enabled
  shell: getenforce | grep -q Disabled || echo yes
  register: selinux_enabled

- name: Set selinux booleans for Galaxy
  seboolean:
    name: "{{item}}"
    state: yes
    persistent: yes
  when: selinux_enabled.stdout == "yes"
  with_items:
  - httpd_can_network_memcache
  - httpd_can_network_connect_db
  - httpd_can_sendmail
  - httpd_can_network_connect
  - nis_enabled
