---
- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install packages 
  yum: 
    name: "{{ item }}"
  with_items: "{{ postgresql_packages }}"

- name: Check if initdb.log exists
  file: path=/var/lib/pgsql/initdb.log
  ignore_errors: True
  register: initdb_exists

- name: Init the postgresql database
  command: postgresql-setup initdb
  when: initdb_exists.state == 'absent'
  
- name: Update postgresql authentication settings
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
  notify: restart postgres 

- name: Update postgresql config settings
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/data/postgresql.conf
    owner: postgres
  notify: restart postgres 

- name: Start and enable postgresql
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Wait for postgresql to be up
  wait_for: port=5432

- name: Create the galaxy user for postgresql
  postgresql_user: name=galaxy password={{ galaxy_postgresql_password }}
  when: initdb_exists.state == 'absent'

- name: Create the galaxy database
  postgresql_db: name=galaxy owner=galaxy
  when: initdb_exists.state == 'absent'
