---
- name: Create a temp directory
  tempfile:
    state: directory
    prefix: galaxy
  register: tempdir
  tags:
  - start
  - stop

- name: Template compose file
  template:
    src: compose.yml.j2
    dest: '{{ tempdir.path }}/docker-compose.yml'
  tags:
  - start
  - stop

- name: Start Galaxy
  docker_service:
    state: present
    project_name: galaxy
    project_src: '{{ tempdir.path }}'
  register: startup
  tags:
  - start
  
- name: Stop Galaxy
  docker_service:
    state: absent 
    project_name: galaxy
    project_src: '{{ tempdir.path }}'
  tags:
  - stop

- name: Remove temp directory
  file:
    state: absent
    path: '{{ tempdir.path }}'
  tags:
  - start
  - stop
