---
- name: Install epel
  yum: 
    name: epel-release
    state: present 

- name: Install packages 
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ rabbit_packages }}"
 
- name: Start and enable the rabbitmq service
  service: name=rabbitmq-server state=restarted enabled=yes

- name: Wait for rabbitmq service to be running
  wait_for: port={{galaxy_rabbit_port}} delay=10

- name: Create the rabbitmq vhost
  rabbitmq_vhost:
    name: "{{galaxy_rabbit_vhost}}"
    state: present

- name: Create the rabbitmq user
  rabbitmq_user:
    user: "{{galaxy_rabbit_username}}"
    password: "{{galaxy_rabbit_password}}"
    vhost: "{{galaxy_rabbit_vhost}}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    force: yes
  notify: Restart rabbitmq
