---

- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install packages
  yum:
    name: "{{ item }}"
  with_items: "{{ supervisor_packages }}"

- name: Enable supervisor
  service:
    name: supervisord
    state: started
    enabled: yes

- name: Add Galaxy Config to supervisord.conf with Beats
  ini_file: 
    dest: "{{sup_conf_location}}"
    section: "program:galaxy-admin"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - option: environment
      value: "DJANGO_SETTINGS_MODULE=galaxy.settings.custom"
    - option: command
      value: "/usr/bin/galaxy-manage celeryd -B -l info -Q admin_tasks,celery --autoscale=8,4"
    - option: directory
      value: "/var/lib/galaxy"
    - option: user
      value: "galaxy"
    - option: autostart
      value: "true"
    - option: autorestart
      value: "true"
    - option: stopwaitsecs
      value: 600
    - option: log_stdout
      value: "true"
    - option: log_stderr
      value: "true"
    - option: stdout_logfile
      value: "/var/log/galaxy/celeryd_admin.log"
    - option: stderr_logfile
      value: "/var/log/galaxy/celeryd_admin.log"
    - option: logfile_maxbytes
      value: 50MB
    - option: logfile_backups
      value: 999
  when: celery_type == 'admin'
  notify: restart supervisor
  tags: supervisor

- name: Add Galaxy Config to supervisord.conf without Beats
  ini_file:
    dest: "{{sup_conf_location}}"
    section: "program:galaxy-user"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - option: environment
      value: "DJANGO_SETTINGS_MODULE=galaxy.settings.custom"
    - option: command
      value: "/usr/bin/galaxy-manage celeryd -l info -Q user_tasks --autoscale=8,4"
    - option: directory
      value: "/var/lib/galaxy"
    - option: user
      value: "galaxy"
    - option: autostart
      value: "true"
    - option: autorestart
      value: "true"
    - option: stopwaitsecs
      value: 600
    - option: log_stdout
      value: "true"
    - option: log_stderr
      value: "true"
    - option: stdout_logfile
      value: "/var/log/galaxy/celeryd_user.log"
    - option: stderr_logfile
      value: "/var/log/galaxy/celeryd_user.log"
    - option: logfile_maxbytes
      value: 50MB
    - option: logfile_backups
      value: 999
  when: celery_type == 'user'
  notify: restart supervisor
  tags: supervisor

- name: Add Galaxy Config to supervisord.conf without Beats
  ini_file:
    dest: "{{sup_conf_location}}"
    section: "program:galaxy-star"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - option: environment
      value: "DJANGO_SETTINGS_MODULE=galaxy.settings.custom"
    - option: command
      value: "/usr/bin/galaxy-manage celeryd -l info -Q star_tasks --autoscale=8,4"
    - option: directory
      value: "/var/lib/galaxy"
    - option: user
      value: "galaxy"
    - option: autostart
      value: "true"
    - option: autorestart
      value: "true"
    - option: stopwaitsecs
      value: 600
    - option: log_stdout
      value: "true"
    - option: log_stderr
      value: "true"
    - option: stdout_logfile
      value: "/var/log/galaxy/celeryd_star.log"
    - option: stderr_logfile
      value: "/var/log/galaxy/celeryd_star.log"
    - option: logfile_maxbytes
      value: 50MB
    - option: logfile_backups
      value: 999
  when: celery_type == 'user'
  notify: restart supervisor
  tags: supervisor

- name: Add Galaxy Config to supervisord.conf without Beats
  ini_file:
    dest: "{{sup_conf_location}}"
    section: "program:galaxy-imports"
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - option: environment
      value: "DJANGO_SETTINGS_MODULE=galaxy.settings.custom"
    - option: command
      value: "/usr/bin/galaxy-manage celeryd -l info -Q import_tasks --autoscale=8,4"
    - option: directory
      value: "/var/lib/galaxy"
    - option: user
      value: "galaxy"
    - option: autostart
      value: "true"
    - option: autorestart
      value: "true"
    - option: stopwaitsecs
      value: 600
    - option: log_stdout
      value: "true"
    - option: log_stderr
      value: "true"
    - option: stdout_logfile
      value: "/var/log/galaxy/celeryd_imports.log"
    - option: stderr_logfile
      value: "/var/log/galaxy/celeryd_imports.log"
    - option: logfile_maxbytes
      value: 50MB
    - option: logfile_backups
      value: 999
  when: celery_type == 'imports'
  notify: restart supervisor
  tags: supervisor
