# tasks/main.yml

- name: Create users 
  user:
    name: "{{ item.username }}" 
    state: present
    createhome: yes
    groups: wheel
    shell: "/bin/bash"
  with_items: "{{ authorized_users }}"

- name: Add authorized keys
  include: auth_keys.yml
  vars:
    user: "{{ item }}"
  with_items: "{{ authorized_users }}"

