# copy_branding.yml
---
- name: Copy templates
  copy:
    src: '{{ item }}'
    dest: '{{ root_path }}/galaxy/templates/'
  with_fileglob:
  - '{{ custom_branding_path }}/templates/*'
  delegate_to: localhost

- name: Copy static/img files 
  copy:
    src: '{{ item }}'
    dest: '{{ root_path }}/galaxy/static/img/'
  with_fileglob:
  - '{{ custom_branding_path }}/img/*'
  delegate_to: localhost

- name: Copy static/less files 
  copy:
    src: '{{ item }}'
    dest: '{{ root_path }}/galaxy/static/less/'
  with_fileglob:
  - '{{ custom_branding_path }}/less/*'
  delegate_to: localhost

- name: Copy static/partials files 
  copy:
    src: '{{ item }}'
    dest: '{{ root_path }}/galaxy/static/partials/'
  with_fileglob:
  - '{{ custom_branding_path }}/partials/*'
  delegate_to: localhost
