#
# Create PostgreSQL datadog user.
#
- name: create sql file
  template:
      src: create_user.sql.j2
      dest: "{{ pgmonitor_tmp}}/create_user.sql"

# The following assumes the .pgpass file exists
- name: create user
  shell: psql -d galaxy -U postgres -f /tmp/create_user.sql
  ignore_errors: yes

- name: remove sql file
  file:
      path: "{{ pgmonitor_tmp}}/create_user.sql"
      state: absent  
